### PR TITLE
changes behavior & add maliciousip blocklist

### PR DESCRIPTION
**Pull request by malikshi**
minimize file size of the rules

### CODE REVIEW

**Comment by malikshi** [comment]
@adisubagja can you tests it?

**Comment by malikshi** [comment]
rule_malicious and rule_maliciousip rejected by default it's not part of trafficads

**Comment by malikshi** [comment]
repo updaterule https://github.com/malikshi/updaterule/commit/3be3a0309ee143392d10384f642f19b8a9e007be

**Comment by adisubagja** [comment]
Nice back update.
Will try after going home

**Comment by adisubagja** [comment]
Working fine for now
Size **YES** this reduced
Ram usage first start/enabled making crazy taking longer & ram eating 1,2GB i think this not for lowest device.
I Think you must try build geodata for ownscript this will make reduce all size,ram,cpu

But now this fine all working hope can have geodata for next updates 😅 i will wait
Thanks you very much for better making rules & block ads

Device : HG680P
RAM : 2GB
Firmware : OpenWRT Reyre AP 20 Latest
Kernel : 5.4.204 (Stock FW)

**Comment by malikshi** [comment]
> Working fine for now Size **YES** this reduced Ram usage first start/enabled making crazy taking longer & ram eating 1,2GB i think this not for lowest device. I Think you must try build geodata for ownscript this will make reduce all size,ram,cpu
> 
> But now this fine all working hope can have geodata for next updates 😅 i will wait Thanks you very much for better making rules & block ads
> 
> Device : HG680P RAM : 2GB Firmware : OpenWRT Reyre AP 20 Latest Kernel : 5.4.204 (Stock FW)

Thank your for tested new update. I been thinking between wildcard and domains. Surely wildard list will make the file much smaller.
Mine are working good and the ram usage only 150MB on openclash dashboard
Screenshot_2022-07-19-12-16-59-591_com android chrome
Can you check if the file already replaced with new one in your device

**Comment by malikshi** [comment]
@adisubagja test again https://github.com/malikshi/open_clash/pull/5 wildcard version are very small compared to non-wildcard

**Comment by adisubagja** [comment]
Good first start taking 300-700mb
image
Then waitting more 3mins here result
image

Nice this more stable now first start no more longer time for running & and faster reduce before previous commit

**Comment by malikshi** [comment]
> But now this fine all working hope can have geodata for next updates 😅 i will wait
> Thanks you very much for better making rules & block ads

Can you share the reference?

**Comment by malikshi** [comment]
> Nice this more stable now first start no more longer time for running & and faster reduce before previous commit

Well done, yes it's much faster now.

**Pull request merged**
